version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --target ./package requests
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd package
      - zip -r ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip function.js
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name my-first-function --zip-file fileb://deployment_package.zip
      - echo "DONE!!"